version: '3.8'

services:
  backend:
    build: ./backend
    container_name: oracle-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://oracle:oracle@db:5432/oracle
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: oracle-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: oracle-db
    environment:
      - POSTGRES_USER=oracle
      - POSTGRES_PASSWORD=oracle
      - POSTGRES_DB=oracle
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: oracle-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  celery:
    build: ./backend
    container_name: oracle-celery
    command: celery -A app.tasks.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://oracle:oracle@db:5432/oracle
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
